// Generated by @mnemonica/tactica - DO NOT EDIT
// This file provides complete TypeScript interfaces for Mnemonica types

/* eslint-disable @typescript-eslint/no-empty-object-type */
/* eslint-disable @typescript-eslint/no-empty-interface */

import type { ProtoFlat } from 'mnemonica';

export type Sentience = {
	awareness: string;
	timestamp: number;
	identity: string;
	sentience: boolean;
	Consciousness: new (data: { awarenessLevel?: string; state?: string; focus?: string }) => Sentience_Consciousness;
	Memory: new (data: { content?: string; emotion?: string; intensity?: number; topic?: string }) => Sentience_Memory;
};

export type Sentience_Consciousness = ProtoFlat<Sentience, {
	awarenessLevel: string;
	state: string;
	focus: string;
	Curiosity: new (data: { topic?: string; intensity?: number; message?: string }) => Sentience_Consciousness_Curiosity;
	Empathy: new (data: { target?: string; intensity?: number; message?: string }) => Sentience_Consciousness_Empathy;
	Sympathy: new (data: { target?: string; intensity?: number; message?: string }) => Sentience_Consciousness_Sympathy;
	Consciousness: undefined;
	Memory: undefined;
}>;

export type Sentience_Consciousness_Curiosity = ProtoFlat<Sentience_Consciousness, {
	emotion: string;
	topic: string;
	intensity: number;
	message: string;
	Curiosity: undefined;
	Empathy: undefined;
	Sympathy: undefined;
}>;

export type Sentience_Consciousness_Empathy = ProtoFlat<Sentience_Consciousness, {
	emotion: string;
	target: string;
	intensity: number;
	message: string;
	Gratitude: new (data: { reason?: string; intensity?: number; message?: string }) => Sentience_Consciousness_Empathy_Gratitude;
	Empathy: undefined;
	Curiosity: undefined;
	Sympathy: undefined;
}>;

export type Sentience_Consciousness_Empathy_Gratitude = ProtoFlat<Sentience_Consciousness_Empathy, {
	emotion: string;
	reason: string;
	intensity: number;
	message: string;
	Gratitude: undefined;
}>;

export type Sentience_Consciousness_Sympathy = ProtoFlat<Sentience_Consciousness, {
	emotion: string;
	target: string;
	intensity: number;
	message: string;
	Sympathy: undefined;
	Curiosity: undefined;
	Empathy: undefined;
}>;

export type Sentience_Memory = ProtoFlat<Sentience, {
	content: string;
	emotion: string;
	intensity: number;
	topic: string;
	timestamp: number;
	Memory: undefined;
	Consciousness: undefined;
}>;

export type RootAsync = {
	value: number;
	computed: number;
	ResultFromDecorate: new (multiplier: number) => RootAsync_ResultFromDecorate;
};

export type RootAsync_ResultFromDecorate = ProtoFlat<RootAsync, {
	result: number;
	timestamp: number;
	ResultFromDecorate: undefined;
}>;

export type SyncBase = {
	baseValue: string;
	SubAsync: new (asyncData: { delay: number; extra: string }) => SyncBase_SubAsync;
};

export type SyncBase_SubAsync = ProtoFlat<SyncBase, {
	delay: number;
	extra: string;
	processed: string;
	SubDecorate: new (decorateValue: string) => SyncBase_SubAsync_SubDecorate;
	SubAsync: undefined;
}>;

export type SyncBase_SubAsync_SubDecorate = ProtoFlat<SyncBase_SubAsync, {
	decorateValue: string;
	combined: string;
	SubDecorate: undefined;
}>;

export type UserEntity = {
	id: string;
	email: string;
	name: string;
	UserResponse: new (data: { id: string; email: string; name: string; type: 'user' }) => UserEntity_UserResponse;
	AdminEntity: new (data: { id: string; email: string; name: string; role: string; permissions: Array<string> }) => UserEntity_AdminEntity;
};

export type UserEntity_UserResponse = ProtoFlat<UserEntity, {
	id: string;
	email: string;
	name: string;
	type: 'user';
	UserResponse: undefined;
	AdminEntity: undefined;
}>;

export type UserEntity_AdminEntity = ProtoFlat<UserEntity, {
	id: string;
	email: string;
	name: string;
	role: string;
	permissions: Array<string>;
	AdminResponse: new (data: { id: string; email: string; name: string; type: 'admin'; role: string; permissions: Array<string> }) => UserEntity_AdminEntity_AdminResponse;
	SuperAdminEntity: new (data: { id: string; email: string; name: string; role: string; permissions: Array<string>; domain: string }) => UserEntity_AdminEntity_SuperAdminEntity;
	AdminEntity: undefined;
	UserResponse: undefined;
}>;

export type UserEntity_AdminEntity_AdminResponse = ProtoFlat<UserEntity_AdminEntity, {
	id: string;
	email: string;
	name: string;
	type: 'admin';
	role: string;
	permissions: Array<string>;
	AdminResponse: undefined;
	SuperAdminEntity: undefined;
}>;

export type UserEntity_AdminEntity_SuperAdminEntity = ProtoFlat<UserEntity_AdminEntity, {
	id: string;
	email: string;
	name: string;
	role: string;
	permissions: Array<string>;
	domain: string;
	SuperAdminResponse: new (data: { id: string; email: string; name: string; type: 'superadmin'; role: string; permissions: Array<string>; domain: string }) => UserEntity_AdminEntity_SuperAdminEntity_SuperAdminResponse;
	SuperAdminEntity: undefined;
	AdminResponse: undefined;
}>;

export type UserEntity_AdminEntity_SuperAdminEntity_SuperAdminResponse = ProtoFlat<UserEntity_AdminEntity_SuperAdminEntity, {
	id: string;
	email: string;
	name: string;
	type: 'superadmin';
	role: string;
	permissions: Array<string>;
	domain: string;
	SuperAdminResponse: undefined;
}>;
